##### BEGIN external-mapped/Dockerfile/image-header #####
FROM docker.elastic.co/beats/metricbeat:7.9.2
##### END external-mapped/Dockerfile/image-header #####

##### BEGIN external/Dockerfile/conteco #####
ENV CONTECO_ENTRYPOINT "/conteco/bin/docker-entrypoint"
COPY ./docker-entrypoint /conteco/bin/docker-entrypoint
##### END external/Dockerfile/conteco #####

##### BEGIN external-mapped/Dockerfile/labels-footer #####
LABEL io.vcweb.schema-version="1.0" \
      io.vcweb.realm="vcwebio" \
      io.vcweb.ecosystem="conteco" \
      io.vcweb.type="external" \
      io.vcweb.name="metricbeat" \
      io.vcweb.tag="7.9.2" \
      io.vcweb.base="docker.elastic.co/beats/metricbeat:7.9.2" \
      io.vcweb.build="external-mapped" \
      io.vcweb.label="external.metricbeat - ContEco" \
      io.vcweb.description="ElasticSearch Metricbeat image with ContEco external prerequisites installed." \
      io.vcweb.repository="/conteco/repo"
##### END external-mapped/Dockerfile/labels-footer #####
