#!/usr/bin/env bash

export CONTECO_LABEL="external.metricbeat - ContEco"
export CONTECO_DESCRIPTION="ElasticSearch Metricbeat image with ContEco external prerequisites installed."

export CONTECO_TYPE="external"
export CONTECO_NAME="metricbeat"
export CONTECO_TAG="7.9.2"

export CONTECO_BASE="docker.elastic.co/beats/metricbeat:7.9.2"
export CONTECO_BUILD="external-mapped"
